### ISSUE TITLE
Port to Redux 1.0 RC

### ISSUE THREAD

**Issue by gaearon** [lapanoid/redux-sync#1]
Redux 1.0 RC has some breaking changes, and should be more suitable for “extension” APIs.
That's why [Redux DevTools](http://github.com/gaearon/redux-devtools) require it.

I think that for any experimental stuff we should use 1.0 RC as it's closest to what we plan to ship.

**Comment by sergey-lapin** [comment]
https://github.com/lapanoid/redux-remote/commit/d1a9a9a8516b73b69c16c977d24ee286d1597c57 - done!

**Comment by gaearon** [comment]
:+1: Thanks!
